name: exercise-2

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3030:3030" 
    environment:
      DATABASE_URI: mongodb://mongo:27017/exercise-2
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017" 